baseurl = "https://anuragaryan.com/"
languageCode = "en-US"
title = "Anurag Aryan"
# Enable comments by entering your Disqus shortname
disqusShortname = "anuragaryan"
# Enable Google Analytics by entering your tracking code
googleAnalytics = "UA-58039575-2"
theme = "minimalistic"

[permalinks]
  post = "/:year/:month/:day/:slug"

[params]
  author = "Anurag Aryan"
  description = "My personal corner on Internet."

  # Custom assets can be linked with their paths relative to static/
  custom_css = ["css/blogpost.css"]
  custom_js  = []

[params.social]
  Github        = "anuragaryan"
  Email         = "anurag.aryan2011@gmail.com"
  Twitter       = "AnuragCodes"
  LinkedIn      = "anuragaryan"
  Stackoverflow = "users/3134957"
  Instagram     = "anuragshows"

## Main Menu
[[menu.main]]
  name = "blog"
  weight = 100
  identifier = "blog"
  url = "/blog/"
[[menu.main]]
  name = "projects"
  identifier = "projects"
  weight = 200
  url = "/projects/"
[[menu.main]]
  name = "resume"
  identifier = "resume"
  weight = 300
  url = "/resume/"
