baseurl = "https://anuragaryan.com/"
locale = "en-US"
title = "Anurag Aryan"

[module]

[[module.imports]]
  path = "github.com/anuragaryan/hugo-theme-minimalistic"

[services]
  [services.disqus]
    shortname = "anuragaryan"

[permalinks]
  post = "/:year/:month/:day/:slug"

[markup]
  [markup.highlight]
    noClasses = false

[params]
  author = "Anurag Aryan"
  description = "My personal corner on Internet."
  homeTitle = "Hi, I'm Anurag."
  homeDescription = """I'm currently working as an Engineering Manager at [Delivery Hero](https://www.deliveryhero.com/).\\
I'm an engineer whose interest also lies in music, finance and rock climbing."""
  darkMode = "auto"

  # Custom assets can be linked with their paths relative to static/
  custom_css = ["css/site.css"]
  custom_js  = []

[params.social]
  Github        = "anuragaryan"
  Email         = "anurag.aryan2011@gmail.com"
  Twitter       = "AnuragCodes"
  LinkedIn      = "anuragaryan"
  Stackoverflow = "users/3134957"
  Instagram     = "anuragshows"

## Main Menu
[[menu.main]]
  name = "blog"
  weight = 100
  identifier = "blog"
  url = "/blog/"
[[menu.main]]
  name = "projects"
  identifier = "projects"
  weight = 200
  url = "/projects/"
