name = "minimalistic"
license = "MIT"
licenselink = ""
description = ""
homepage = ""
tags = []
features = []
min_version = 0.1

[author]
  name = "Anurag Aryan"
  homepage = ""

# If porting an existing theme
[original]
  name = ""
  homepage = ""
  repo = ""
